services:
  backend:
    build: ./backend
    container_name: video_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: video_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  backend_data:
  backend_uploads: